# Generated by Django 3.0.5 on 2020-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_class', models.CharField(max_length=200)),
                ('Monthly_fees', models.IntegerField()),
            ],
        ),
    ]
